services:
  spring-batch:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: springbatch
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
